[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
blue = "0x6CB6EB"
cyan = "0x5DBBC1"
green = "0xA0C980"
magenta = "0xD38AEA"
red = "0xEC7279"
white = "0xC5CDD9"
yellow = "0xDEB974"

[colors.normal]
black = "0x363A49"
blue = "0x6CB6EB"
cyan = "0x5DBBC1"
green = "0xA0C980"
magenta = "0xD38AEA"
red = "0xEC7279"
white = "0xC5CDD9"
yellow = "0xDEB974"

[colors.primary]
background = "0x2B2D37"
foreground = "0xC5CDD9"

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "ComicCode Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Monaspace Argon"
style = "Bold Italic"

[font.italic]
family = "Monaspace Argon"
style = "Italic"

[font.normal]
family = "ComicCode Nerd Font"
style = "Regular"

[scrolling]
history = 100000
multiplier = 4

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[terminal.shell]
args = ["--login"]
program = "/opt/homebrew/bin/fish"

[window]
decorations = "transparent"
option_as_alt = "Both"

[window.dimensions]
columns = 106
lines = 24

[window.padding]
x = 10
y = 27

[general]
live_config_reload = true

[terminal]
